Newlines preserved in commands

diff --git a/charts/ontopic-suite/templates/jobs/users.yaml b/charts/ontopic-suite/templates/jobs/users.yaml
--- a/charts/ontopic-suite/templates/jobs/users.yaml
+++ b/charts/ontopic-suite/templates/jobs/users.yaml
@@ -93,16 +93,16 @@ spec:
         command:
         - "sh"
         - "-c"
-        - >-
-            NAME="password-db-users"
-            FILE="/mnt/secret/${NAME}"
-            printf '%s' {{- printf "{\"users\": %s}" (.Values.users.list | toJson) | toJson }} > "$FILE"
+        - |
+            NAME="password-db-users";
+            FILE="/mnt/secret/${NAME}";
+            printf '%s' {{- printf "{\"users\": %s}" (.Values.users.list | toJson) | toJson }} > "$FILE";
             if [ -f "$FILE" ]; then
-              kubectl delete secret "$NAME" --ignore-not-found
-              kubectl create secret generic "$NAME" --from-file=users="$FILE"
+              kubectl delete secret "$NAME" --ignore-not-found;
+              kubectl create secret generic "$NAME" --from-file=users="$FILE";
             else
-              echo "Error: File $FILE was not created"
-              exit 1
+              echo "Error: File $FILE was not created";
+              exit 1;
             fi
             exit 0
         volumeMounts:
@@ -167,7 +167,7 @@ spec:
         command:
         - "sh"
         - "-c"
-        - >-
+        - |
             FILE="/mnt/secret/password-file-db";
             NAME="password-file-db";
             if [ -f "$FILE" ]; then
